// SPDX-FileCopyrightText: Copyright (c) 2026 kanri-sync contributors
//
// SPDX-License-Identifier: GPL-3.0-or-later

// Applies kanri-sync's Android customisations to the project generated by
// `tauri android init` (src-tauri/gen/android):
//  * permissions for Wi-Fi state and multicast (needed for LAN discovery)
//  * a MainActivity that holds a Wi-Fi MulticastLock while the app runs;
//    without it Android silently drops the mDNS packets used to find devices.
// Safe to run more than once.

import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

const root = "src-tauri/gen/android/app/src/main";

const manifestPath = join(root, "AndroidManifest.xml");
let manifest = readFileSync(manifestPath, "utf8");
const permissions = [
  "android.permission.ACCESS_NETWORK_STATE",
  "android.permission.ACCESS_WIFI_STATE",
  "android.permission.CHANGE_WIFI_MULTICAST_STATE",
];
for (const p of permissions) {
  if (!manifest.includes(`"${p}"`)) {
    manifest = manifest.replace(
      /<application/,
      `<uses-permission android:name="${p}" />\n    <application`,
    );
  }
}
writeFileSync(manifestPath, manifest);

const findFile = (dir, name) => {
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry);
    if (statSync(p).isDirectory()) {
      const found = findFile(p, name);
      if (found) return found;
    } else if (entry === name) {
      return p;
    }
  }
  return null;
};

const activityPath = findFile(join(root, "java"), "MainActivity.kt");
if (!activityPath) throw new Error("MainActivity.kt not found; did `tauri android init` run?");
const original = readFileSync(activityPath, "utf8");
const pkg = original.match(/^package\s+([\w.]+)/m)?.[1];
if (!pkg) throw new Error("Could not determine package of MainActivity.kt");

writeFileSync(
  activityPath,
  `package ${pkg}

import android.content.Context
import android.net.wifi.WifiManager
import android.os.Bundle
import android.view.View
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat

class MainActivity : TauriActivity() {
  private var multicastLock: WifiManager.MulticastLock? = null

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    // Android 15+ draws apps edge-to-edge and no longer shrinks them when the
    // on-screen keyboard opens, so text fields end up hidden behind it. Pad
    // the content by the keyboard height so the web view resizes above it.
    val content = findViewById<View>(android.R.id.content)
    ViewCompat.setOnApplyWindowInsetsListener(content) { v, insets ->
      val ime = insets.getInsets(WindowInsetsCompat.Type.ime())
      v.setPadding(0, 0, 0, ime.bottom)
      insets
    }
    // Kanri Sync finds other devices with mDNS; Android drops multicast
    // packets unless an app holds this lock.
    try {
      val wifi = applicationContext.getSystemService(Context.WIFI_SERVICE) as WifiManager
      multicastLock = wifi.createMulticastLock("kanri-sync-mdns").apply {
        setReferenceCounted(false)
        acquire()
      }
    } catch (e: Exception) {
      android.util.Log.w("KanriSync", "Could not acquire multicast lock", e)
    }
  }

  override fun onDestroy() {
    multicastLock?.let { if (it.isHeld) it.release() }
    super.onDestroy()
  }
}
`,
);

console.log(`Patched ${manifestPath} and ${activityPath}`);
